-- 0001_initial.sql — generated by db/gen_pg_schema.py from the 0.5.0 sqlite schema (see docstring). Do not edit applied files.

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mabaniq_app') THEN CREATE ROLE mabaniq_app NOLOGIN NOBYPASSRLS; END IF; END $$;

CREATE TABLE projects(
  id bigserial PRIMARY KEY, code text, name text, location text, kind text,
  build_pct double precision, planned_monthly_sales double precision, handover text, land_id bigint, completed bigint DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, code)
);

CREATE TABLE units(
  id bigserial PRIMARY KEY, project_id bigint REFERENCES projects(id), code text,
  building text, floor bigint, pos bigint, type text, area double precision, view text,
  price double precision, status text CHECK(status IN ('a','r','s')), retained bigint DEFAULT 0, use text DEFAULT 'residential',
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, code)
);

CREATE TABLE customers(
  id bigserial PRIMARY KEY, name text, phone text, created text, rescheduled bigint DEFAULT 0,
  id_type text, id_number text, nationality text, id_expiry text, dob text, pep bigint DEFAULT 0,
  source_of_funds text, kyc_status text DEFAULT 'pending', kyc_risk text, kyc_note text, kyc_at text,
  consent_at text, email text, consent_version text, consent_source text, erased_at text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE leads(
  id bigserial PRIMARY KEY, name text, phone text, interest text, project_id bigint REFERENCES projects(id),
  channel text, stage bigint, interactions bigint, budget double precision, created text, last_contact text, score bigint,
  broker_id bigint, bedrooms bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE bookings(
  id bigserial PRIMARY KEY, unit_id bigint REFERENCES units(id), customer_id bigint REFERENCES customers(id),
  lead_id bigint, plan text, price double precision, status text CHECK(status IN ('pending','confirmed','cancelled')),
  created text, expires text, broker_id bigint, list_price double precision, handed_over text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE installments(
  id bigserial PRIMARY KEY, booking_id bigint REFERENCES bookings(id), seq bigint, label text,
  due_date text, amount double precision, paid_amount double precision DEFAULT 0, paid_date text, penalty_waived bigint DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE contractors(
  id bigserial PRIMARY KEY, name text, cr_number text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE ipcs(
  id bigserial PRIMARY KEY, project_id bigint REFERENCES projects(id), contractor_id bigint REFERENCES contractors(id),
  no bigint, stage text, claimed_pct double precision, stage_value double precision, status text, approved_pct double precision, created text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE ipc_items(
  id bigserial PRIMARY KEY, ipc_id bigint REFERENCES ipcs(id), item text, weight double precision, verified_pct double precision, evidence bigint,
  verified_by text, method text DEFAULT 'engineer',
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE cost_schedule(
  id bigserial PRIMARY KEY, project_id bigint REFERENCES projects(id), month text, amount double precision, label text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE decisions_log(
  key text, action text, at text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , PRIMARY KEY (org_id, key)
);

CREATE TABLE audit(
  id bigserial PRIMARY KEY, at text, actor text, action text, detail text, prev_hash text, hash text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE settings(
  k text, v text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , PRIMARY KEY (org_id, k)
);

CREATE TABLE service_requests(
  id bigserial PRIMARY KEY, booking_id bigint REFERENCES bookings(id), category text, description text,
  status text CHECK(status IN ('new','in_progress','done')), created text, updated text, note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE resale(
  id bigserial PRIMARY KEY, booking_id bigint REFERENCES bookings(id), ask_price double precision, fee double precision,
  status text CHECK(status IN ('pending','listed','rejected','sold')), created text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE payments(
  id bigserial PRIMARY KEY, installment_id bigint REFERENCES installments(id), amount double precision, at text, method text, receipt text,
  gateway_ref text, reconciled bigint DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, gateway_ref)
);

CREATE TABLE lands(
  id bigserial PRIMARY KEY, name text, location text, area double precision, zoning text, far double precision, max_floors bigint,
  price double precision, status text, lat double precision, lng double precision, notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE feasibility(
  id bigserial PRIMARY KEY, land_id bigint, name text, inputs text, results text, created text, by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE permits(
  id bigserial PRIMARY KEY, project_id bigint, authority text, kind text, ref text, status text,
  applied text, issued text, expires text, notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE contracts_c(
  id bigserial PRIMARY KEY, project_id bigint, contractor_id bigint, value double precision, retention_pct double precision,
  delay_penalty_per_day double precision, start text, finish text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE schedule_tasks(
  id bigserial PRIMARY KEY, project_id bigint, name text, planned_start text, planned_end text,
  actual_start text, actual_end text, pct double precision, depends_on bigint, weight double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE change_orders(
  id bigserial PRIMARY KEY, project_id bigint, no bigint, title text, reason text, cost double precision, days bigint,
  status text, requested text, decided text, decided_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE site_reports(
  id bigserial PRIMARY KEY, project_id bigint, day text, workers bigint, weather text, work_done text,
  issues text, photos bigint, by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE ncrs(
  id bigserial PRIMARY KEY, project_id bigint, title text, severity text, status text, raised text, closed text, location text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE budgets(
  id bigserial PRIMARY KEY, project_id bigint, category text, amount double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE sale_contracts(
  id bigserial PRIMARY KEY, booking_id bigint UNIQUE, number text, body text, sha256 text, status text,
  created text, customer_signed_at text, customer_sig text, developer_signed_at text, developer_sig text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE discount_requests(
  id bigserial PRIMARY KEY, booking_id bigint, pct double precision, reason text, status text, requested_by text,
  decided_by text, created text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE brokers(
  id bigserial PRIMARY KEY, name text, license_no text, phone text, rate double precision, active bigint DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE commissions(
  id bigserial PRIMARY KEY, broker_id bigint, booking_id bigint UNIQUE, amount double precision, status text, paid_at text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE watchlist(
  id bigserial PRIMARY KEY, name text, source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE resale_offers(
  id bigserial PRIMARY KEY, resale_id bigint, buyer_name text, buyer_phone text, price double precision, status text, created text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE viewings(
  id bigserial PRIMARY KEY, lead_id bigint, project_id bigint, at text, status text, source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE wa_messages(
  id bigserial PRIMARY KEY, phone text, direction text, body text, at text, lead_id bigint, engine text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE invoices(
  id bigserial PRIMARY KEY, number text, kind text, ref_type text, ref_id bigint, customer text,
  net double precision, vat_rate double precision, vat double precision, total double precision, issued text, note text, customer_id bigint REFERENCES customers(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, number)
);

CREATE TABLE refunds(
  id bigserial PRIMARY KEY, booking_id bigint, paid double precision, deducted double precision, refund double precision, status text, created text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE pay_intents(
  id text, installment_id bigint, amount double precision, status text, created text, provider text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , PRIMARY KEY (org_id, id)
);

CREATE TABLE bank_lines(
  id bigserial PRIMARY KEY, day text, amount double precision, reference text, matched_payment bigint, imported text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE distributions(
  id bigserial PRIMARY KEY, project_id bigint, investor text, amount double precision, day text, note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE snags(
  id bigserial PRIMARY KEY, booking_id bigint, item text, location text, status text, raised text, closed text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE handovers(
  id bigserial PRIMARY KEY, booking_id bigint UNIQUE, appointment text, status text, certificate_no text,
  handed_at text, warranty_until text, structural_until text, meter_readings text, keys bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE titles(
  id bigserial PRIMARY KEY, booking_id bigint UNIQUE, status text, fee double precision, applied text, deed_no text, issued text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE fm_assets(
  id bigserial PRIMARY KEY, project_id bigint, name text, category text, last_service text, interval_days bigint,
  installed text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE work_orders(
  id bigserial PRIMARY KEY, asset_id bigint, kind text, title text, due text, status text, done text, cost double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE oa_budget(
  id bigserial PRIMARY KEY, project_id bigint, year bigint, line text, amount double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE oa_charges(
  id bigserial PRIMARY KEY, project_id bigint, booking_id bigint, year bigint, amount double precision, paid double precision DEFAULT 0, issued text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE oa_motions(
  id bigserial PRIMARY KEY, project_id bigint, title text, opened text, closes text, status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE oa_votes(
  motion_id bigint, booking_id bigint, vote text, weight double precision, at text, PRIMARY KEY(motion_id, booking_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE tenants_l(
  id bigserial PRIMARY KEY, name text, phone text, id_number text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE leases(
  id bigserial PRIMARY KEY, unit_id bigint, tenant_id bigint, start text, "end" text, annual_rent double precision,
  frequency bigint, deposit double precision, status text, municipality_ref text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE rent_dues(
  id bigserial PRIMARY KEY, lease_id bigint, due text, amount double precision, paid double precision DEFAULT 0, paid_date text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE documents(
  id bigserial PRIMARY KEY, ref_type text, ref_id bigint, title text, category text, filename text, mime text,
  size bigint, sha256 text, stored text, uploaded_by text, at text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE notifications(
  id bigserial PRIMARY KEY, audience text, customer_id bigint, channel text, title text, body text,
  status text, created text, dedupe text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, dedupe)
);

CREATE TABLE api_keys(
  id bigserial PRIMARY KEY, name text, key_hash text, prefix text, created text, last_used text, active bigint DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, key_hash)
);

CREATE TABLE reset_tokens(
  token_hash text, user_id bigint, expires double precision, used bigint DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , PRIMARY KEY (org_id, token_hash)
);

CREATE TABLE privacy_requests(
  id bigserial PRIMARY KEY, customer_id bigint, kind text, status text, created text, note text, decided_at text, decided_by text, decision_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE charity_dues(
  id bigserial PRIMARY KEY, installment_id bigint UNIQUE REFERENCES installments(id), customer_id bigint, amount double precision, rate double precision,
  late_days bigint, computed_at text, status text CHECK(status IN ('due','collected','disbursed','waived')) DEFAULT 'due',
  collected_at text, collected_ref text, disbursed_at text, beneficiary text, disbursed_ref text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE resale_settlements(
  id bigserial PRIMARY KEY, resale_id bigint UNIQUE, booking_id bigint, seller_customer_id bigint, buyer_customer_id bigint,
  price double precision, seller_paid double precision, unpaid_installments double precision, equity_due_to_seller double precision, fee double precision,
  status text CHECK(status IN ('open','settled')) DEFAULT 'open', created text, settled_at text, reference text, settled_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE TABLE users(
  id bigserial PRIMARY KEY, username text, name text, role text, pw text, customer_id bigint, broker_id bigint,
  active bigint DEFAULT 1, must_change bigint DEFAULT 0, totp_secret text, totp_enabled bigint DEFAULT 0,
  totp_last bigint DEFAULT 0, pw_changed text,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , UNIQUE (org_id, username)
);

CREATE TABLE sessions(
  token_hash text, user_id bigint REFERENCES users(id), expires double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
  , PRIMARY KEY (org_id, token_hash)
);

CREATE TABLE auth_failures(
  k text, at double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)
);

CREATE INDEX IF NOT EXISTS ix_inv_customer ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS ix_units_project ON units(project_id);
CREATE INDEX IF NOT EXISTS ix_inst_booking ON installments(booking_id);
CREATE INDEX IF NOT EXISTS ix_book_unit ON bookings(unit_id);
CREATE INDEX IF NOT EXISTS ix_book_customer ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS ix_auth_failures ON auth_failures(k, at);

-- append-only audit (sqlite triggers → plpgsql guard; demo reseed sets app.maintenance for the transaction)
CREATE OR REPLACE FUNCTION mabaniq_audit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF current_setting('app.maintenance', true) = '1' THEN RETURN COALESCE(NEW, OLD); END IF;
  RAISE EXCEPTION 'audit is append-only';
END $$;
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit FOR EACH ROW EXECUTE FUNCTION mabaniq_audit_guard();
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit FOR EACH ROW EXECUTE FUNCTION mabaniq_audit_guard();

-- row-level security per developer organisation (org_id) on every table — `leases.tenant_id` is the lessee, unrelated
CREATE INDEX IF NOT EXISTS ix_projects_org ON projects(org_id);
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
CREATE POLICY projects_org ON projects USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_units_org ON units(org_id);
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
ALTER TABLE units FORCE ROW LEVEL SECURITY;
CREATE POLICY units_org ON units USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_customers_org ON customers(org_id);
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers FORCE ROW LEVEL SECURITY;
CREATE POLICY customers_org ON customers USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_leads_org ON leads(org_id);
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads FORCE ROW LEVEL SECURITY;
CREATE POLICY leads_org ON leads USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_bookings_org ON bookings(org_id);
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings FORCE ROW LEVEL SECURITY;
CREATE POLICY bookings_org ON bookings USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_installments_org ON installments(org_id);
ALTER TABLE installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE installments FORCE ROW LEVEL SECURITY;
CREATE POLICY installments_org ON installments USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_contractors_org ON contractors(org_id);
ALTER TABLE contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractors FORCE ROW LEVEL SECURITY;
CREATE POLICY contractors_org ON contractors USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_ipcs_org ON ipcs(org_id);
ALTER TABLE ipcs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ipcs FORCE ROW LEVEL SECURITY;
CREATE POLICY ipcs_org ON ipcs USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_ipc_items_org ON ipc_items(org_id);
ALTER TABLE ipc_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE ipc_items FORCE ROW LEVEL SECURITY;
CREATE POLICY ipc_items_org ON ipc_items USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_cost_schedule_org ON cost_schedule(org_id);
ALTER TABLE cost_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_schedule FORCE ROW LEVEL SECURITY;
CREATE POLICY cost_schedule_org ON cost_schedule USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_decisions_log_org ON decisions_log(org_id);
ALTER TABLE decisions_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE decisions_log FORCE ROW LEVEL SECURITY;
CREATE POLICY decisions_log_org ON decisions_log USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_audit_org ON audit(org_id);
ALTER TABLE audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_org ON audit USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_settings_org ON settings(org_id);
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings FORCE ROW LEVEL SECURITY;
CREATE POLICY settings_org ON settings USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_service_requests_org ON service_requests(org_id);
ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY service_requests_org ON service_requests USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_resale_org ON resale(org_id);
ALTER TABLE resale ENABLE ROW LEVEL SECURITY;
ALTER TABLE resale FORCE ROW LEVEL SECURITY;
CREATE POLICY resale_org ON resale USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_payments_org ON payments(org_id);
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
CREATE POLICY payments_org ON payments USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_lands_org ON lands(org_id);
ALTER TABLE lands ENABLE ROW LEVEL SECURITY;
ALTER TABLE lands FORCE ROW LEVEL SECURITY;
CREATE POLICY lands_org ON lands USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_feasibility_org ON feasibility(org_id);
ALTER TABLE feasibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE feasibility FORCE ROW LEVEL SECURITY;
CREATE POLICY feasibility_org ON feasibility USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_permits_org ON permits(org_id);
ALTER TABLE permits ENABLE ROW LEVEL SECURITY;
ALTER TABLE permits FORCE ROW LEVEL SECURITY;
CREATE POLICY permits_org ON permits USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_contracts_c_org ON contracts_c(org_id);
ALTER TABLE contracts_c ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts_c FORCE ROW LEVEL SECURITY;
CREATE POLICY contracts_c_org ON contracts_c USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_schedule_tasks_org ON schedule_tasks(org_id);
ALTER TABLE schedule_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY schedule_tasks_org ON schedule_tasks USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_change_orders_org ON change_orders(org_id);
ALTER TABLE change_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE change_orders FORCE ROW LEVEL SECURITY;
CREATE POLICY change_orders_org ON change_orders USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_site_reports_org ON site_reports(org_id);
ALTER TABLE site_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_reports FORCE ROW LEVEL SECURITY;
CREATE POLICY site_reports_org ON site_reports USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_ncrs_org ON ncrs(org_id);
ALTER TABLE ncrs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ncrs FORCE ROW LEVEL SECURITY;
CREATE POLICY ncrs_org ON ncrs USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_budgets_org ON budgets(org_id);
ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets FORCE ROW LEVEL SECURITY;
CREATE POLICY budgets_org ON budgets USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_sale_contracts_org ON sale_contracts(org_id);
ALTER TABLE sale_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_contracts FORCE ROW LEVEL SECURITY;
CREATE POLICY sale_contracts_org ON sale_contracts USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_discount_requests_org ON discount_requests(org_id);
ALTER TABLE discount_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE discount_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY discount_requests_org ON discount_requests USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_brokers_org ON brokers(org_id);
ALTER TABLE brokers ENABLE ROW LEVEL SECURITY;
ALTER TABLE brokers FORCE ROW LEVEL SECURITY;
CREATE POLICY brokers_org ON brokers USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_commissions_org ON commissions(org_id);
ALTER TABLE commissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE commissions FORCE ROW LEVEL SECURITY;
CREATE POLICY commissions_org ON commissions USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_watchlist_org ON watchlist(org_id);
ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchlist FORCE ROW LEVEL SECURITY;
CREATE POLICY watchlist_org ON watchlist USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_resale_offers_org ON resale_offers(org_id);
ALTER TABLE resale_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE resale_offers FORCE ROW LEVEL SECURITY;
CREATE POLICY resale_offers_org ON resale_offers USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_viewings_org ON viewings(org_id);
ALTER TABLE viewings ENABLE ROW LEVEL SECURITY;
ALTER TABLE viewings FORCE ROW LEVEL SECURITY;
CREATE POLICY viewings_org ON viewings USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_wa_messages_org ON wa_messages(org_id);
ALTER TABLE wa_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE wa_messages FORCE ROW LEVEL SECURITY;
CREATE POLICY wa_messages_org ON wa_messages USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_invoices_org ON invoices(org_id);
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
CREATE POLICY invoices_org ON invoices USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_refunds_org ON refunds(org_id);
ALTER TABLE refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE refunds FORCE ROW LEVEL SECURITY;
CREATE POLICY refunds_org ON refunds USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_pay_intents_org ON pay_intents(org_id);
ALTER TABLE pay_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE pay_intents FORCE ROW LEVEL SECURITY;
CREATE POLICY pay_intents_org ON pay_intents USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_bank_lines_org ON bank_lines(org_id);
ALTER TABLE bank_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY bank_lines_org ON bank_lines USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_distributions_org ON distributions(org_id);
ALTER TABLE distributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE distributions FORCE ROW LEVEL SECURITY;
CREATE POLICY distributions_org ON distributions USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_snags_org ON snags(org_id);
ALTER TABLE snags ENABLE ROW LEVEL SECURITY;
ALTER TABLE snags FORCE ROW LEVEL SECURITY;
CREATE POLICY snags_org ON snags USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_handovers_org ON handovers(org_id);
ALTER TABLE handovers ENABLE ROW LEVEL SECURITY;
ALTER TABLE handovers FORCE ROW LEVEL SECURITY;
CREATE POLICY handovers_org ON handovers USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_titles_org ON titles(org_id);
ALTER TABLE titles ENABLE ROW LEVEL SECURITY;
ALTER TABLE titles FORCE ROW LEVEL SECURITY;
CREATE POLICY titles_org ON titles USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_fm_assets_org ON fm_assets(org_id);
ALTER TABLE fm_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE fm_assets FORCE ROW LEVEL SECURITY;
CREATE POLICY fm_assets_org ON fm_assets USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_work_orders_org ON work_orders(org_id);
ALTER TABLE work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders FORCE ROW LEVEL SECURITY;
CREATE POLICY work_orders_org ON work_orders USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_oa_budget_org ON oa_budget(org_id);
ALTER TABLE oa_budget ENABLE ROW LEVEL SECURITY;
ALTER TABLE oa_budget FORCE ROW LEVEL SECURITY;
CREATE POLICY oa_budget_org ON oa_budget USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_oa_charges_org ON oa_charges(org_id);
ALTER TABLE oa_charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE oa_charges FORCE ROW LEVEL SECURITY;
CREATE POLICY oa_charges_org ON oa_charges USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_oa_motions_org ON oa_motions(org_id);
ALTER TABLE oa_motions ENABLE ROW LEVEL SECURITY;
ALTER TABLE oa_motions FORCE ROW LEVEL SECURITY;
CREATE POLICY oa_motions_org ON oa_motions USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_oa_votes_org ON oa_votes(org_id);
ALTER TABLE oa_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE oa_votes FORCE ROW LEVEL SECURITY;
CREATE POLICY oa_votes_org ON oa_votes USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_tenants_l_org ON tenants_l(org_id);
ALTER TABLE tenants_l ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants_l FORCE ROW LEVEL SECURITY;
CREATE POLICY tenants_l_org ON tenants_l USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_leases_org ON leases(org_id);
ALTER TABLE leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE leases FORCE ROW LEVEL SECURITY;
CREATE POLICY leases_org ON leases USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_rent_dues_org ON rent_dues(org_id);
ALTER TABLE rent_dues ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_dues FORCE ROW LEVEL SECURITY;
CREATE POLICY rent_dues_org ON rent_dues USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_documents_org ON documents(org_id);
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
CREATE POLICY documents_org ON documents USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_notifications_org ON notifications(org_id);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications FORCE ROW LEVEL SECURITY;
CREATE POLICY notifications_org ON notifications USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_api_keys_org ON api_keys(org_id);
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY api_keys_org ON api_keys USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_reset_tokens_org ON reset_tokens(org_id);
ALTER TABLE reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE reset_tokens FORCE ROW LEVEL SECURITY;
CREATE POLICY reset_tokens_org ON reset_tokens USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_privacy_requests_org ON privacy_requests(org_id);
ALTER TABLE privacy_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE privacy_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY privacy_requests_org ON privacy_requests USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_charity_dues_org ON charity_dues(org_id);
ALTER TABLE charity_dues ENABLE ROW LEVEL SECURITY;
ALTER TABLE charity_dues FORCE ROW LEVEL SECURITY;
CREATE POLICY charity_dues_org ON charity_dues USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_resale_settlements_org ON resale_settlements(org_id);
ALTER TABLE resale_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE resale_settlements FORCE ROW LEVEL SECURITY;
CREATE POLICY resale_settlements_org ON resale_settlements USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_users_org ON users(org_id);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
CREATE POLICY users_org ON users USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_sessions_org ON sessions(org_id);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
CREATE POLICY sessions_org ON sessions USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));
CREATE INDEX IF NOT EXISTS ix_auth_failures_org ON auth_failures(org_id);
ALTER TABLE auth_failures ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_failures FORCE ROW LEVEL SECURITY;
CREATE POLICY auth_failures_org ON auth_failures USING (org_id = current_setting('app.org_id', true)) WITH CHECK (org_id = current_setting('app.org_id', true));

GRANT USAGE ON SCHEMA public TO mabaniq_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mabaniq_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mabaniq_app;
REVOKE ALL ON schema_migrations FROM mabaniq_app;
-- the audit table: no UPDATE/DELETE grant at all (the guard is belt and braces)
REVOKE UPDATE, DELETE ON audit FROM mabaniq_app;
