"""Generate db/migrations/0001_initial.sql (PostgreSQL) from the sqlite SCHEMA in backend/db.py + backend/auth.py.

Run once (`python db/gen_pg_schema.py`) and commit the output. Later schema changes are new migration files written by
hand; this generator documents how the initial PostgreSQL schema was derived from the 0.5.0 sqlite model.

Transformations
- `id INTEGER PRIMARY KEY` → `id bigserial PRIMARY KEY`; `INTEGER` → `bigint`; `REAL` → `double precision`; `TEXT` → `text`.
- Every table gets trailing columns `created_at timestamptz NOT NULL DEFAULT now()` and
  `tenant_id text NOT NULL DEFAULT current_setting('app.tenant_id', true)` (trailing, so positional INSERTs keep working).
- Per-tenant uniqueness: single-column UNIQUE / text PRIMARY KEY constraints become composite with `tenant_id`.
- Row-level security enabled **and forced** on every table with a tenant policy; role `mabaniq_app` (NOLOGIN,
  NOBYPASSRLS) gets DML grants; the app connects as any login role and `SET ROLE mabaniq_app`.
- sqlite audit triggers become a plpgsql guard that honours the transaction-local `app.maintenance` flag (demo reseed).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.auth import USERS_SQL  # noqa: E402
from backend.db import SCHEMA  # noqa: E402

TENANT_UNIQUE = {"units": ["code"], "projects": ["code"], "users": ["username"], "invoices": ["number"], "payments": ["gateway_ref"],
                 "notifications": ["dedupe"], "api_keys": ["key_hash"]}
TENANT_PK = {"settings": "k", "sessions": "token_hash", "decisions_log": "key", "reset_tokens": "token_hash", "pay_intents": "id"}


def convert_table(name: str, body: str) -> str:
    cols = body.strip()
    cols = re.sub(r"\bid INTEGER PRIMARY KEY\b", "id bigserial PRIMARY KEY", cols)
    cols = re.sub(r"\bINTEGER\b", "bigint", cols)
    cols = re.sub(r"\bREAL\b", "double precision", cols)
    cols = re.sub(r"\bTEXT\b", "text", cols)
    # single-column UNIQUE → composite with tenant
    for col in TENANT_UNIQUE.get(name, []):
        cols = re.sub(rf"(\b{col} text) UNIQUE", r"\1", cols)
    if name in TENANT_PK:
        pk = TENANT_PK[name]
        cols = re.sub(rf"(\b{pk} text) PRIMARY KEY", r"\1", cols)
    cols = re.sub(r"\bend text\b", '"end" text', cols)  # reserved word in PostgreSQL (leases.end)
    out = [f"CREATE TABLE {name}(", "  " + cols + ",", "  created_at timestamptz NOT NULL DEFAULT now(),",
           "  org_id text NOT NULL DEFAULT current_setting('app.org_id', true)"]
    if name in TENANT_PK:
        out.append(f"  , PRIMARY KEY (org_id, {TENANT_PK[name]})")
    for col in TENANT_UNIQUE.get(name, []):
        out.append(f"  , UNIQUE (org_id, {col})")
    out.append(");")
    return "\n".join(out)


def main() -> str:
    src = SCHEMA + "\n" + USERS_SQL
    parts = ["-- 0001_initial.sql — generated by db/gen_pg_schema.py from the 0.5.0 sqlite schema (see docstring). Do not edit applied files.",
             "", "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mabaniq_app') THEN CREATE ROLE mabaniq_app NOLOGIN NOBYPASSRLS; END IF; END $$;", ""]
    tables: list[str] = []
    for m in re.finditer(r"CREATE TABLE IF NOT EXISTS (\w+)\((.*?)\);", src, re.S):
        tables.append(m.group(1))
        parts.append(convert_table(m.group(1), m.group(2)))
        parts.append("")
    for m in re.finditer(r"CREATE INDEX IF NOT EXISTS (\w+) ON (\w+)\(([^)]*)\);", src):
        parts.append(f"CREATE INDEX IF NOT EXISTS {m.group(1)} ON {m.group(2)}({m.group(3)});")
    parts.append("")
    parts.append("""-- append-only audit (sqlite triggers → plpgsql guard; demo reseed sets app.maintenance for the transaction)
CREATE OR REPLACE FUNCTION mabaniq_audit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF current_setting('app.maintenance', true) = '1' THEN RETURN COALESCE(NEW, OLD); END IF;
  RAISE EXCEPTION 'audit is append-only';
END $$;
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit FOR EACH ROW EXECUTE FUNCTION mabaniq_audit_guard();
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit FOR EACH ROW EXECUTE FUNCTION mabaniq_audit_guard();
""")
    parts.append("-- row-level security per developer organisation (org_id) on every table — `leases.tenant_id` is the lessee, unrelated")
    for t in tables:
        parts.append(f"CREATE INDEX IF NOT EXISTS ix_{t}_org ON {t}(org_id);")
        parts.append(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;")
        parts.append(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY;")
        parts.append(f"CREATE POLICY {t}_org ON {t} USING (org_id = current_setting('app.org_id', true)) "
                     f"WITH CHECK (org_id = current_setting('app.org_id', true));")
    parts.append("")
    parts.append("GRANT USAGE ON SCHEMA public TO mabaniq_app;")
    parts.append("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mabaniq_app;")
    parts.append("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mabaniq_app;")
    parts.append("REVOKE ALL ON schema_migrations FROM mabaniq_app;")
    parts.append("-- the audit table: no UPDATE/DELETE grant at all (the guard is belt and braces)")
    parts.append("REVOKE UPDATE, DELETE ON audit FROM mabaniq_app;")
    parts.append("")
    return "\n".join(parts)


if __name__ == "__main__":
    out = ROOT / "db" / "migrations" / "0001_initial.sql"
    out.write_text(main(), encoding="utf-8", newline="\n")
    print("wrote", out, len(main().splitlines()), "lines")
